IF OBJECT_ID('Werehouse') IS NOT NULL
	DROP DATABASE Werehouse;
GO
CREATE DATABASE Werehouse
GO
IF OBJECT_ID('bronze') IS NOT NULL
	DROP SCHEMA bronze;
GO
CREATE SCHEMA bronze;
GO
IF OBJECT_ID('silver') IS NOT NULL
	DROP SCHEMA silver;
GO
CREATE SCHEMA silver;
GO
IF OBJECT_ID('gold') IS NOT NULL
	DROP SCHEMA gold;
GO
CREATE SCHEMA gold;
GO